---
services:
  node-alice:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: node_alice
    cap_add:
      - NET_ADMIN                      # Nutné pro tun0
    devices:
      - /dev/net/tun:/dev/net/tun      # Přístup k TUN zařízení
    environment:
      RUST_LOG: info,iroh=warn
    networks:
      vpn_test_net:
        ipv4_address: 172.25.0.2
    volumes:
      - ./data/keys/alice.raw:/keys/alice.raw
      - ../target/debug/zeroconf-p2p-vpn:/zeroconf-p2p-vpn
    entrypoint:
      - /zeroconf-p2p-vpn
      - keys/alice.raw

  node-bob:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: node_bob
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      RUST_LOG: info,iroh=warn
    networks:
      vpn_test_net:
        ipv4_address: 172.25.0.3
    volumes:
      - ./data/keys/bob.raw:/keys/bob.raw
      - ../target/debug/zeroconf-p2p-vpn:/zeroconf-p2p-vpn
    entrypoint:
      - /zeroconf-p2p-vpn
      - keys/bob.raw
      - ri5s1riaxztowkfasg645kdngnugembhsjwke5qfrktno9qjn8ty

networks:
  vpn_test_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

