use anyhow::Result;
use ipnet::{IpNet, Ipv4Net, Ipv6Net};
use iroh::{PublicKey, SecretKey, Signature};
use std::io::{Error, ErrorKind};
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};

/// A randomly-generated 40-bit Global ID within the 0xfd00
/// https://en.wikipedia.org/wiki/Unique_local_address. All traffic of this VPN is expected to be
/// only within this (very large) network.
/// The default Subnet ID is 0, but clients can choose their own SubnetID (16-bit) in case of
/// (unlikely) 64-bit collisions in the default 0 subnet.
pub const VPN_IPV6_PREFIX: Ipv6Net =
    Ipv6Net::new_assert(Ipv6Addr::new(0xfdbd, 0xa6ce, 0x654d, 0, 0, 0, 0, 0), 48);

/// Generates an IP address within the given subnet based on a digital signature.
///
/// 1. The address is serialized
///    a. The prefix length of `net` as 1 byte.
///    b. The full network part of `net` as big-endian (BE) bytes; that is, 32 bytes for IPv6 and 4
///       bytes for IPv4.
/// 2. Signature is computed from this message.
/// 3. The trailing bytes of the signature are used to generate the host part of the new IP address.
///    - In case this ends up an IPv4 broadcast address (all bits 1), it's decremented by 1.
///
/// This ensures that
/// - The address is computed in a deterministic manner by the secret key owner.
/// - Is but cryptographically unpredictable and pseudo-random.
/// - Can be verified by anyone knowing the public key.
pub fn generate_signed_ip(net: &IpNet, secret_key: &SecretKey) -> (IpAddr, Signature) {
    let signature = secret_key.sign(&serialize_network(net));
    let ip = generate_signed_ip_with_signature(net, &signature);
    (ip, signature)
}

/// Verifies that the provided IP address matches the signature generated by the given public key for its subnet.
pub fn verify_signed_ip(
    ip: IpAddr,
    prefix_len: u8,
    public_key: &PublicKey,
    signature: &Signature,
) -> Result<()> {
    verify_signed_ipnet(IpNet::new(ip, prefix_len)?, public_key, signature)
}

/// Verifies that the provided IP address matches the signature generated by the given public key for its subnet.
pub fn verify_signed_ipnet(
    net: IpNet,
    public_key: &PublicKey,
    signature: &Signature,
) -> Result<()> {
    let base_net = net.trunc();
    let network_bytes = serialize_network(&base_net);
    public_key.verify(&network_bytes, signature)?;
    let gen_addr = generate_signed_ip_with_signature(&base_net, signature);
    if net.addr() == gen_addr {
        Ok(())
    } else {
        let msg = format!(
            "Address {} doesn't match the generated signature address {}",
            net, gen_addr
        );
        Err(Error::new(ErrorKind::PermissionDenied, msg).into())
    }
}

/// Serialize the network putting the prefix length as the FIRST byte and then in the network
/// (big-endian) format.
fn serialize_network(net: &IpNet) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(17);
    bytes.push(net.prefix_len());
    match net {
        IpNet::V4(net4) => bytes.extend_from_slice(&net4.addr().octets()),
        IpNet::V6(net6) => bytes.extend_from_slice(&net6.addr().octets()),
    };
    bytes
}

/// Derive the IP address from an existing signature.
fn generate_signed_ip_with_signature(net: &IpNet, signature: &Signature) -> IpAddr {
    let signature_bytes = signature.to_bytes();
    let entropy_128 = u128::from_be_bytes(signature_bytes[48..64].try_into().unwrap());
    match net {
        IpNet::V4(net4) => {
            let entropy_32 = entropy_128 as u32;
            IpAddr::V4(derive_ipv4(net4, entropy_32))
        }
        IpNet::V6(net6) => IpAddr::V6(derive_ipv6(net6, entropy_128)),
    }
}

fn derive_ipv4(net: &Ipv4Net, entropy: u32) -> Ipv4Addr {
    let net_mask = u32::from(net.netmask());
    let net_bits = u32::from(net.addr()) & net_mask;
    let host_bits = entropy & !net_mask;

    let mut final_bits = net_bits | host_bits;
    if final_bits == u32::from(net.broadcast()) {
        final_bits &= !1u32;
    }
    Ipv4Addr::from(final_bits)
}

fn derive_ipv6(net: &Ipv6Net, entropy: u128) -> Ipv6Addr {
    let net_mask = u128::from(net.netmask());
    let net_bits = u128::from(net.addr()) & net_mask;
    let host_bits = entropy & !net_mask;
    Ipv6Addr::from(net_bits | host_bits)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    #[test]
    fn test_ipv4_workflow_happy_path() {
        // 1. Setup Alice's secret key and the desired network
        let secret_key = SecretKey::generate();
        let public_key = secret_key.public();
        let net = IpNet::from_str("192.168.1.0/24").unwrap();

        // 2. Alice generates her signed IP address and the signature
        let (alice_ip, signature) = generate_signed_ip(&net, &secret_key);

        // Verify the generated IP is actually within the requested subnet
        assert!(net.contains(&alice_ip));

        // 3. Bob receives the IP, prefix length, public key, and signature, then verifies it
        let prefix_len = net.prefix_len();
        verify_signed_ip(alice_ip, prefix_len, &public_key, &signature)
            .expect("Bob should successfully verify Alice's IP and signature");
    }

    #[test]
    fn test_ipv6_workflow_happy_path() {
        let secret_key = SecretKey::generate();
        let public_key = secret_key.public();
        let net = IpNet::from_str("2001:db8::/64").unwrap();

        let (alice_ip, signature) = generate_signed_ip(&net, &secret_key);
        assert!(net.contains(&alice_ip));

        verify_signed_ipnet(
            IpNet::with_netmask(alice_ip, net.netmask()).unwrap(),
            &public_key,
            &signature,
        )
        .expect("Bob should successfully verify Alice's IPv6 and signature");
    }

    #[test]
    fn test_verification_fails_with_wrong_public_key() {
        let alice_key = SecretKey::generate();
        let charlie_key = SecretKey::generate(); // Intruder/Wrong key
        let net = IpNet::from_str("10.0.0.0/8").unwrap();

        let (alice_ip, signature) = generate_signed_ip(&net, &alice_key);

        // Bob tries to verify Alice's IP using Charlie's public key
        let result = verify_signed_ip(
            alice_ip,
            net.prefix_len(),
            &charlie_key.public(),
            &signature,
        );
        assert!(
            result.is_err(),
            "Verification must fail when using a different public key"
        );
    }

    #[test]
    fn test_verification_fails_if_alice_spoofs_ip() {
        let secret_key = SecretKey::generate();
        let net = IpNet::from_str("172.16.0.0/16").unwrap();

        let (real_ip, signature) = generate_signed_ip(&net, &secret_key);
        let IpAddr::V4(real_ip) = real_ip else {
            panic!("Expected an IPv4 address: {}", real_ip);
        };

        // Alice tries to claim she got a different IP within the same subnet
        let spoofed_ip = IpAddr::V4(Ipv4Addr::from_bits(real_ip.to_bits() ^ 1u32));

        let result = verify_signed_ip(
            spoofed_ip,
            net.prefix_len(),
            &secret_key.public(),
            &signature,
        );
        assert!(
            result.is_err_and(|e| e
                .downcast_ref::<Error>()
                .map_or(false, |io| io.kind() == ErrorKind::PermissionDenied)),
            "Verification must fail if the IP doesn't match the deterministic derivation"
        );
    }

    #[test]
    fn test_ipv4_broadcast_collision_handling() {
        let secret_key = SecretKey::generate();

        // We use the smallest subnet where broadcast collision is highly probable if we run it in a
        // loop, or we just verify that the function never returns the broadcast address.
        let net = IpNet::from_str("192.168.42.0/31").unwrap();
        let broadcast_ip = net.broadcast();

        // Run multiple generations to ensure that even if the signature entropy would naturally
        // map to a broadcast address, the mitigation kicks in.
        for _ in 0..100 {
            let (ip, _) = generate_signed_ip(&net, &secret_key);
            assert_ne!(
                ip, broadcast_ip,
                "Generated IP must never be the broadcast address"
            );
        }
    }
}
